### ISSUE TITLE
Cycle through no box, empty box, and full box

### ISSUE THREAD

**Issue by benbrastmckie** [nfrid/markdown-togglecheck#1]
Hey there, this is great! I need something almost this simple, so very happy to find this plugin.

However, I would like to be able to cycle through the following types of list items:
```
- list item with no box
- [ ] list item with an empty box
- [x] list item with an full box
```
Might it be possible to achieve this with your plugin. Or even without the pluggin, might it be possible to achieve this by adding something to my config file for treesitter? Any thoughts would be much appreciated.

**Comment by nfrid** [comment]
done, now it will create a box by default if there is none + added toggle_box method to do it manually
in case if you need to remove checkbox from checked state instead of unchecking it, you must redefine opts like this:
```
require('markdown-togglecheck').setup({
  remove = true,
})
```

**Comment by benbrastmckie** [comment]
Works great! Thanks so much!

**Comment by benbrastmckie** [comment]
One other question... I've been hunting around for an equally simple plugin which can add bullet points to match above upon creating a new line. (OrgMode looks like way more than I need.) For instance if the list looks like:

```
- stuff to do
  - [ ] still working on it
  - [x] something I finished 
```
Then by creating a new line I would get:
```
- stuff to do
  - [ ] still working on it
  - [x] something I finished 
  - a new line
```
I could then add an empty box and cycle through check marks using your plugin.

What I'm wondering is if this is best handled by a plugin, or if there is an easy way to get this sort of functionality by just adding something to my config. For instance, it might be nice to have different things happen in different file types, i.e., latex vs markdown. Any thoughts would be greatly appreciated!

**Comment by nfrid** [comment]
there is a plugin called [autolist.nvim](https://github.com/gaoDean/autolist.nvim), I use it myself and it works flawlessly for me

**Comment by benbrastmckie** [comment]
Ideal. I'm not sure how I didn't find autolist.nvim before but it is just what I was looking for.

I'm not sure if you are interested, but it occurred to me that your plugin would make a nice PR to autolist.nvim. These two plugins seem to belong together. It would also reduce the number of plugins that needed to be required/maintained etc., from three (you have two) down to just one. Just a thought :)

Thanks again for your help!
