### ISSUE TITLE
Feature request: visual mode support

### ISSUE THREAD

**Issue by mawkler** [nfrid/markdown-togglecheck#4]
It would be awesome if I could toggle multiple checkmarks at once with select mode. Let's say that I have three empty checkboxes like so:

```markdown
- [ ] foo
- [ ] bar
- [ ] baz
```

If I then select all thre with `vip` and trigger the toggle, I would like all three to be checked:

```markdown
- [x] foo
- [x] bar
- [x] baz
```

**Comment by nfrid** [comment]
you can just use `norm[al]` command and set your visual mode keymaps like that:
```lua
  vim.keymap.set('v', '<leader>nn', ":'<,'>norm 1 nn<cr>", { desc = 'Toggle Checkmark' })
  vim.keymap.set('v', '<leader>nN', ":'<,'>norm 1 nN<cr>", { desc = 'Toggle Checkbox' })
```
note that in order to start your `:norm` command with a space (I use it for my leader key) you should prefix it with a number of said spaces, so `:norm 1 nn` will execute `<space>nn` in normal mode

**Comment by mawkler** [comment]
@nfrid That works, thank you very much!
